hex_bot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  FL_servo_1_controller:
    type: effort_controllers/JointPositionController
    joint: FL_servo_1_to_body_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  FL_servo_2_controller:
    type: effort_controllers/JointPositionController
    joint: FL_servo_2_to_FL_servo_1_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  FL_servo_3_controller:
    type: effort_controllers/JointPositionController
    joint: FL_servo_3_to_FL_femur_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  FR_servo_1_controller:
    type: effort_controllers/JointPositionController
    joint: FR_servo_1_to_body_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  FR_servo_2_controller:
    type: effort_controllers/JointPositionController
    joint: FR_servo_2_to_FR_servo_1_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  FR_servo_3_controller:
    type: effort_controllers/JointPositionController
    joint: FR_servo_3_to_FR_femur_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  ML_servo_1_controller:
    type: effort_controllers/JointPositionController
    joint: ML_servo_1_to_body_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  ML_servo_2_controller:
    type: effort_controllers/JointPositionController
    joint: ML_servo_2_to_ML_servo_1_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  ML_servo_3_controller:
    type: effort_controllers/JointPositionController
    joint: ML_servo_3_to_ML_femur_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  MR_servo_1_controller:
    type: effort_controllers/JointPositionController
    joint: MR_servo_1_to_body_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  MR_servo_2_controller:
    type: effort_controllers/JointPositionController
    joint: MR_servo_2_to_MR_servo_1_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  MR_servo_3_controller:
    type: effort_controllers/JointPositionController
    joint: MR_servo_3_to_MR_femur_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  BL_servo_1_controller:
    type: effort_controllers/JointPositionController
    joint: BL_servo_1_to_body_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  BL_servo_2_controller:
    type: effort_controllers/JointPositionController
    joint: BL_servo_2_to_BL_servo_1_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  BL_servo_3_controller:
    type: effort_controllers/JointPositionController
    joint: BL_servo_3_to_BL_femur_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  BR_servo_1_controller:
    type: effort_controllers/JointPositionController
    joint: BR_servo_1_to_body_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  BR_servo_2_controller:
    type: effort_controllers/JointPositionController
    joint: BR_servo_2_to_BR_servo_1_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}

  BR_servo_3_controller:
    type: effort_controllers/JointPositionController
    joint: BR_servo_3_to_BR_femur_joint
    pid: {p: 100.0, i: 0.00, d: 0.0}
