hex_bot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  LEG_servo_1_controller:
    type: effort_controllers/JointPositionController
    joint: LEG_servo_1_to_body_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  LEG_servo_2_controller:
    type: effort_controllers/JointPositionController
    joint: LEG_servo_2_to_LEG_servo_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  LEG_servo_3_controller:
    type: effort_controllers/JointPositionController
    joint: LEG_servo_3_to_LEG_femur_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
